### PR TITLE
Make named parameter parsing use byte slices

### PR DESCRIPTION
**Pull request by glittershark**
As discussed in blackbeam/mysql_async#194, MySQL actually accepts
arbitrary byte slices, not just strings, as queries. This commit is the
first in a cross-repo, likely ongoing effort to update both mysql_common
and mysql_async to accept *either* byte slices or strings - that
distinction is planned on the mysql_async side, but for now this updates
the main entrypoint for queries in this crate, which is
`pares_named_params`, to take `&[u8]` instead of `&str`.

This PR is intended to go along with a similar PR in `mysql_async` to update it
to work with these new APIs

### CODE REVIEW

**Comment by glittershark** [comment]
note that this *is* a breaking change.

**Comment by turkerali** [comment]
Hi there,
I don't if this is the offending commit, but after upgrading to mysql_common to 0.29, all code which uses FromValue and ToValue for "chrono::NaiveDate" type fails miserably as below.  Please note that the "exact code" builds fine with mysql_common 0.28.2

**CASE 1**
--------------------------
error[E0277]: the trait bound `chrono::NaiveDate: FromValue` is not satisfied
   --> src\eni_db.rs:210:27
    |
210 |             ENI_WORKPACK_DATE: row.take("ENI_WORKPACK_DATE").unwrap(),
    |                                    ^^^^ the trait `FromValue` is not implemented for `chrono::NaiveDate`
    |
    = note: required because of the requirements on the impl of `FromValue` for `std::option::Option<chrono::NaiveDate>`
note: required by a bound in `mysql::Row::take`
   --> C:\Users\turkerali\.cargo\registry\src\github.com-1ecc6299db9ec823\mysql_common-0.28.2\src\row\mod.rs:130:12
    |
130 |         T: FromValue,
    |            ^^^^^^^^^ required by this bound in `mysql::Row::take`

**CASE 2**
--------------------------
error[E0599]: the method `to_value` exists for struct `chrono::NaiveDate`, but its trait bounds were not satisfied
   --> src\eni_db.rs:472:148
    |
472 | ...E,"%Y-%m-%d").unwrap().to_value()});
    |                           ^^^^^^^^ method cannot be called on `chrono::NaiveDate` due to unsatisfied trait bounds
    |
   ::: C:\Users\turkerali\.cargo\registry\src\github.com-1ecc6299db9ec823\chrono-0.4.19\src\naive\date.rs:99:1
    |
99  | pub struct NaiveDate {
    | --------------------
    | |
    | doesn't satisfy `chrono::NaiveDate: Into<mysql::Value>`
    | doesn't satisfy `chrono::NaiveDate: mysql::prelude::ToValue`
    |
    = note: the following trait bounds were not satisfied:
            `chrono::NaiveDate: Into<mysql::Value>`
            which is required by `chrono::NaiveDate: mysql::prelude::ToValue`

**Comment by blackbeam** [comment]
@turkerali

> note: required by a bound in mysql::Row::take
--> C:\Users\turkerali.cargo\registry\src\github.com-1ecc6299db9ec823\mysql_common-0.28.2\src\row\mod.rs:130:12

This seem to refer to 0.28.2 even though your version is updated to 0.29.0. It it somehow possible that you are using multiple versions of mysql_common (direclty or via some dependency)?

**Comment by turkerali** [comment]
Hi again.
You are 100% right. Here is the cargo tree output:

|->mysql v22.1.0
|-------->mysql_common v0.28.2
|->mysql_common v0.29.0

As you can see above, there are 2 mysql_common crates involved. Mysql crate pulls "mysql_common v0.28.2" automatically, which does not provide the chrono feature. The second mysql_common is coming from my config.toml:

[dependencies]
mysql = "*"
mysql_common = {version = "0.28.2", features = ["chrono"]}  -----> WORKS
mysql_common = {version = "*", features = ["chrono"]}   -----> FAILS

What is the proper solution here? Should I continue using the old mysql_common?
Thanks in advance.

**Comment by blackbeam** [comment]
Yeah. You should continue to use the old one because the `mysql` crate is not yet updated.
